server:
  port: -1

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: root

app:
  ip:
  ws:
    port: -1
    enable: true
  tcp:
    port: -1
    enable: true
  zk:
    path: /muchat/node
    address: localhost:2181